

export PSR1=$PWD/"LdpcEncDec"


export OPENLANE_ROOT=$PSR1/asic/openlane
export PDK_ROOT=$PSR1/asic/pdk
export PDK=sky130B
#export MCW_ROOT=$PSR1/mgmt_core_wrapper


export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
export DOCKER_DEFAULT_PLATFORM=linux/amd64


export CARAVEL_ROOT=$PWD/caravel
#export CARAVEL_PATH=$CARAVEL_ROOT/../caravel/verilog
#export VERILOG_PATH=$PWD/mgmt_core_wrapper/verilog
#export USER_PROJECT_VERILOG=$CARAVEL_ROOT/../verilog

#unsetenv PSR1 OPENLANE_ROOT PDK_ROOT PDK MCW_ROOT DOCKER_BUILDKIT COMPOSE_DOCKER_CLI_BUILD DOCKER_DEFAULT_PLATFORM CARAVEL_ROOT CARAVEL_PATH VERILOG_PATH USER_PROJECT_VERILOG 
#echo $PSR1 $OPENLANE_ROOT $PDK_ROOT $PDK $MCW_ROOT $DOCKER_BUILDKIT $COMPOSE_DOCKER_CLI_BUILD $DOCKER_DEFAULT_PLATFORM $CARAVEL_ROOT $CARAVEL_PATH $VERILOG_PATH $USER_PROJECT_VERILOG 

